{"status": "failed", "name": "Sing in with invalid email and password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Sing In"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1557481697123, "historyId": "349a634e6b58b350d7117e4549e65623", "start": 1557481681286, "steps": [{"status": "passed", "start": 1557481681303, "stop": 1557481689978, "name": "Given I navigate to home page"}, {"status": "passed", "start": 1557481689979, "stop": 1557481695642, "name": "When I sing in with email:ruxi and pass: 1234"}, {"status": "passed", "start": 1557481695642, "stop": 1557481696954, "name": "When I press the Sing In button"}, {"status": "failed", "start": 1557481696955, "stop": 1557481697122, "name": "Then Verify if the expected error message: Invalid email address. is displayed", "statusDetails": {"message": "AssertionError: The error message is displayed\n", "trace": "  File \"c:\\python27\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\python27\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"test_cases\\steps\\sing_in_steps.py\", line 31, in step_impl\n    assert_equal(expected_message, sing_in.get_errot_message, \"The error message is displayed\")\n  File \"c:\\python27\\lib\\unittest\\case.py\", line 513, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"c:\\python27\\lib\\unittest\\case.py\", line 925, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"c:\\python27\\lib\\unittest\\case.py\", line 410, in fail\n    raise self.failureException(msg)\n"}}], "statusDetails": {"message": "AssertionError: The error message is displayed\n", "trace": "  File \"c:\\python27\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\python27\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"test_cases\\steps\\sing_in_steps.py\", line 31, in step_impl\n    assert_equal(expected_message, sing_in.get_errot_message, \"The error message is displayed\")\n  File \"c:\\python27\\lib\\unittest\\case.py\", line 513, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"c:\\python27\\lib\\unittest\\case.py\", line 925, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"c:\\python27\\lib\\unittest\\case.py\", line 410, in fail\n    raise self.failureException(msg)\n"}, "uuid": "69071266-230c-46f1-9504-b28241ce033c"}