{"status": "failed", "name": "Sing in with valid email and password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Sing In"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1557481703826, "historyId": "337d6c9fb45f9194dcc7dfe6531519a6", "start": 1557481697170, "steps": [{"status": "passed", "start": 1557481697173, "stop": 1557481700108, "name": "Given I navigate to home page"}, {"status": "passed", "start": 1557481700108, "stop": 1557481702678, "name": "When I sing in with email:ruxi.ierima@gmail.com and pass: 1234"}, {"status": "passed", "start": 1557481702678, "stop": 1557481703767, "name": "When I press the Sing In button"}, {"status": "failed", "start": 1557481703768, "stop": 1557481703826, "name": "Then Verify if the expected error message: Authentication failed. is displayed", "statusDetails": {"message": "AssertionError: The error message is displayed\n", "trace": "  File \"c:\\python27\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\python27\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"test_cases\\steps\\sing_in_steps.py\", line 31, in step_impl\n    assert_equal(expected_message, sing_in.get_errot_message, \"The error message is displayed\")\n  File \"c:\\python27\\lib\\unittest\\case.py\", line 513, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"c:\\python27\\lib\\unittest\\case.py\", line 925, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"c:\\python27\\lib\\unittest\\case.py\", line 410, in fail\n    raise self.failureException(msg)\n"}}], "statusDetails": {"message": "AssertionError: The error message is displayed\n", "trace": "  File \"c:\\python27\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\python27\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"test_cases\\steps\\sing_in_steps.py\", line 31, in step_impl\n    assert_equal(expected_message, sing_in.get_errot_message, \"The error message is displayed\")\n  File \"c:\\python27\\lib\\unittest\\case.py\", line 513, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"c:\\python27\\lib\\unittest\\case.py\", line 925, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"c:\\python27\\lib\\unittest\\case.py\", line 410, in fail\n    raise self.failureException(msg)\n"}, "uuid": "87c8a0ce-fe97-4055-a7eb-16491888f528"}